networks:
  microservice-net:
    driver: bridge

services:
  xbde-frame:
    build: ./xbde-gui
    container_name: xbde-frame
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - microservice-net
    restart: unless-stopped



