name: xbde
services:
  xbde-frame:
    build: ./xbde-gui
    container_name: xbde-frame
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - microservice-net
    restart: unless-stopped

  tdms-uploader:
    build: .
    container_name: tdms-uploader
    ports:
      - "8508:8080"
    volumes:
      - ./uploads:/app/uploads
      - ./converted:/app/converted
    networks:
      - xbde-network

networks:
  xbde-network:
    driver: bridge



